# List of directories to read into Oolong
note_directories = [
    "~/notes",
]

# Subdirectory patterns to exclude from the file watcher
ignored_directories = [
    ".git",
    ".templates",
    "target",
]

# Whitelist of file extensions to use in linking
allowed_extensions = [
    ".md",
    ".mdx",
    ".tex",
    ".typ",
]

# Command to run when open endpoint it called (a note node is clicked on the graph)
open_command = [ "code" ]
# Note: All arguments MUST be separated into separate strings
# (more complicated commands should likely be written into a script)
# i.e. 'open_command = ["tmux", "neww", "-c", "shell", "nvim"]'

# Range of NGram sizes to use for keyword linking
ngram_range = [ 1, 2, 3 ]

# Additional stop words
stop_words = [
    "hello",
]

# List of plugins (lua files) to load -- not recommended
[plugins]
plugin_paths = [ "./scripts/daily_note.lua" ]

[graph]
min_node_weight = 4.0
max_node_weight = 80.0
min_link_weight = 0.1

#
# NOTE: do not include the following section if you do not want to use cloud sync
#
[sync]
host = "127.0.0.1" # replace with your server hostname/ip
user = "your_username" # replace with your server username
port = 22 # server ssh port
private_key_path = "/home/<your_username>/.ssh/<your_private_key_file>" # replace with your private key path
